# To launch tensorboard in dir tensorboard --logdir=./

# TRAINING CONSTANTS
GAMMA = 0.99
OBSERVATION_SIZE = 84*84
ACTIONS_SIZE = 7
LOAD_MODEL = False
MODEL_PATH = './model'

# VIZDOOM CONSTANTS
BOTS = 7
RENDER_HUD = False
RENDER_CROSSHAIR = False
RENDER_WEAPON = True
RENDER_DECALS = False
RENDER_PARTICLES = False
EPISODE_TIMEOUT = 25200
EPISODE_START_TIME = 10
WINDOW_VISIBLE = True
SOUND_ENABLED = False